- [] Make basic UI
- [] Connect APIS (Google Maps, FEMA, etc)
- [] Search bar/autofill dropdown to select type of emergency
- [] Route to closest shelter/hospital/etc.
- [] Option to bypass search and just look at map
- [] List on side (from FEMA) of current disasters in your county
- [] Disasters are clickable to reroute/route to the nearest relief shelter for that disaster & also include links for other sources related to disaster
